- name: install apache2 package (Debian)
  tags: apache,apache2,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Debian"

- name: install httpd package (Rocky) 
  tags: apache,rocky,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "Rocky"

- name: start and enable httpd (Rocky)
  tags: apache,rocky,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Rocky"

- name: change e-mail address for admin
  tags: apache,rocky,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Rocky"
  register: httpd

- name: restart httpd (Rocky)
  tags: apache,rocky,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
