- name: install mariadb package (Rocky)
  tags: db,mariadb,rocky
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Rocky"

- name: install mariadb package (debian)
  tags: db,mariadb,debian
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Debian"
